---
title: "Admin Calls"
author: "Pierre Saouter"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Admin Calls}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(QualtricsInR)
```

This document describes wrapper functions for API calls reserved to users with administration level rights to their organization account.

## Retrieve organization account information 

Gets general information about an organization (or brand). See the documentation to retrieve your organization id.

```
library(QualtricsInR)
get_organization()
```

## Create a new division

You can create a new division at the organization level. The only mandatory paremeter is the name of the new division. You can also pass a list of 
user ids (see get_users()) with admin rights for this division. Finally, you can define the divisions permissions,
otherwise default permissions will be set. The call returns the id of the created division.

```
div_id <- create_division("New_Division", list("UR_1234567890AbCdE"))
```

You can retrieve or update a given division. The best way to figure out the permissions you have accessible for the first call
is to retrieve an exisiting division from Qualtrics and study the json reply below.

```
json_rep <- get_division("DV_1234567890AbCdE")
update_division("DV_1234567890AbCdE", name = "New_Name")
```

## Manage user groups

```
df <- list_groups()
```

## Manage users

A useful function is to list all users. This request can take time for large organizations as the query will loop through
all paginations available.

```
df <- list_users()
```
