---
title: "Surveys"
author: "Pierre Saouter"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Surveys}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Manipulating Survey Objects

Using the Qualtrics API, you can peform a number of manipulations of survey objects in your Qualtrics account. You can check all available actions at the Qualtrics API reference webpage [here](https://api.qualtrics.com/reference/get-brand-info). We provide below a brief descriptions of a non exhaustive list of actions available in the package for the manipulation of surveys:

* List surveys
* Retrieving a survey
* Updating a survey
* Deleting a survey
* Importing a survey
* Copying a survey within an account and to other accounts
* Sharing a survey with other accounts

### Listing surveys in Account

You can easily retrieve the full list of surveys available in your account:

``` r
my_surveys <- list_surveys()
```

This allows you to easily search for the survey_id of the survey of interest in order to interact with the object remotely. For example, you can copy a survey within your account or to another account:

``` r
# Copy a survey in your own account
copy_survey(my_surveys[1], "New_Copy")
# Copy a survey to another user's account
copy_survey(my_surveys[1], "New_Copy",user_id)
```

You might not want to copy a survey into another person's account but would rather share the project defining a specific set
of permissions. By default, without any specification, your project will be shared with all permissions disabled. You can decide which permissions to enable by providing an array of numbers indicating the permissions you want to enable. The available options are listed below:

``` r
"1"="copySurveyQuestions"
"2"="editSurveyFlow"
"3"="useBlocks"
"4"="useSkipLogic"
"5"="useConjoint"
"6"="useTriggers"
"7"="useQuotas"
"8"="setSurveyOptions"
"9"="editQuestions"
"10"="deleteSurveyQuestions"
"11"="editSurveys"
"12"="activateSurveys"
"13"="deactivateSurveys"
"14"="copySurveys"
"15"="distributeSurveys"
"16"="deleteSurveys"
"17"="translateSurveys"
"18"="editSurveyResponses"
"19"="createResponseSets"
"20"="viewResponseId"
"21"="useCrossTabs"
"22"="downloadSurveyResults"
"23"="viewSurveyResults"
"24"="filterSurveyResults"
"25"="viewPersonalData"
```

As an example, to share the survey with only distribution rights enabled, you run the following call:

``` r
share_survey(my_surveys[1], user_id, 15)
```

Previous calls are overridden by any new permissions setting so you must set every permission each time. To add permissions to visualize the data, do:

``` r
# enable permissions for distribution and data visualisation
share_survey(my_surveys[1], user_id, c(15,23))
# remove permission to visualize the data
share_survey(my_surveys[1], user_id, c(15))
```
