

#' List all survey questions
#'
#' @param survey_id the survey id
#' @examples
#' \dontrun{list_questions("SV_012345678901234")}
#' @return A list
#' @export
list_questions <- function(survey_id) {
  params <- c("survey-definitions", survey_id, "questions")
  getcnt <- .qualtrics_get(params)
  getcnt$result
}

#' Retrieve a survey question
#'
#' @param survey_id the survey id
#' @param question_id the question id see list_questions
#'
#' @examples
#' \dontrun{get_survey_question("SV_012345678901234","QID1")}
#' @return A list
#' @export
get_survey_question <- function(survey_id, question_id) {
  params <- c("survey-definitions", survey_id, "questions", question_id)
  getcnt <- .qualtrics_get(params)
  getcnt$result
}

#' Delete a survey question
#'
#' @param survey_id the survey id
#' @param question_id the question id see list_questions
#' @examples
#' \dontrun{delete_survey_question("SV_012345678901234","QID1")}
#' @return A list
#' @export
delete_survey_question <- function(survey_id, question_id) {
  params <- c("survey-definitions", survey_id, "questions", question_id)
  getcnt <- .qualtrics_delete(params, NULL, NULL)
  getcnt$meta$httpStatus
}

#' Get survey question mapping
#' 
#' @description 
#' This function returns a tibble formatted result of the list_question result, allowing for an easy
#' inspection of the relation between question IDs and question export tags.
#'
#' @param survey_id the survey id
#' @examples
#' \dontrun{get_questions_mapping("SV_012345678901234")}
#' @return A list
#' @export
get_questions_mapping <- function(survey_id) {

  qmap <- list_questions(survey_id)

  do.call(
    bind_rows,
    lapply(
      qmap$elements,
      function(x) {
        tibble(
          "QuestionID" = x$QuestionID,
          "DataExportTag" = x$DataExportTag,
          "QuestionType" = x$QuestionType,
          "QuestionDescription" = x$QuestionDescription
        )
      }))

}


#' Generate a compatible question id
#' 
#' @description 
#' When uploading a new question to a survey (see `upload_question`), it can be convenient 
#' to control the creation of the question id locally. This convenience function returns a 
#' question id that is unique and does not overlap with existing question ids in the survey. 
#' It's simple increment of the numeric part of the question ids.
#'
#' @param survey_id the survey id
#'
#' @examples
#' \dontrun{
#' generate_question_id(
#' "SV_012345678901234", 
#' )
#' }
#' @return A string of the form QID1
#' @export
generate_question_id <- function(survey_id) {
  
  list_questions <- get_questions_mapping(survey_id) %>%
    mutate(index = as.integer(gsub("QID", "", QuestionID)))

  paste0("QID", max(list_questions$index)+1)

}


#' Create a survey question
#' 
#' @description
#' Allows to create a new survey question within an existing. If the block does not
#' exist, please create the block first using `create_block`.
#'
#' @param survey_id the survey id
#' @param block_id the block id of the block where the question will be created
#' @param question nested list of parameters defining the question
#'
#' @examples
#' \dontrun{get_survey_question("SV_012345678901234","QID1")}
#' @return A list
#' @export
create_survey_question <- function(survey_id, question_id) {
  params <- c("survey-definitions", survey_id, "questions", question_id)
  getcnt <- .qualtrics_get(params)
  getcnt$result
}


#' Generate a compatible question data export tag
#' 
#' @description 
#' Control the data export tag associated with a question. In general the value
#' should be associated with the corresponding question id, such that a question
#' with id QID2 has a Data Export Tag value of Q1 or QID1 or Q.1.
#'
#' @param survey_id the survey id
#'
#' @examples
#' \dontrun{
#' generate_question_id(
#' "SV_012345678901234", 
#' )
#' }
#' @return A string of the form QID1
generate_question_export_tag <- function(survey_id) {
  
  list_questions <- get_questions_mapping(survey_id) %>%
    mutate(index = as.integer(gsub("QID", "", QuestionID)))

  paste0("QID", max(list_questions$index)+1)

}



upload_question <- function(srv_id, q_object, q_exporttag = NULL, q_id = NULL) {

  questions <- get_questions_mapping(srv_id)

  if (!is.null(q_exporttag) & q_exporttag %in% questions$DataExportTag)
    stop("You provided an export tag that already exists. Pass q_exporttag as NULL to get an autogenerated one.")

  if (!is.null(q_id) & q_id %in% questions$QuestionID)
    stop("You provided an export tag that already exists. Pass q_id as NULL to get an autogenerated one.")

  if (is.null(q_id)) {
    q_id <- generate_question_id(srv_id)
  } 

}
